#
# doxygen example
#
#
# This file is part of the processing.make project.
#

BASE_DIR=../../..
include $(BASE_DIR)/processing.mk

# include the extension
include $(BASE_DIR)/processing.make.extensions/doxygen.mk
